import type { ClientProfile } from "@/types";

export const DEFAULT_CLIENT_PROFILE: Omit<ClientProfile, "id" | "name" | "createdAt" | "updatedAt"> = {
  h2Color: "#000000",
  h2FontSize: "32px",
  h2LineHeight: "1.4",
  h2Bold: true,
  h3Color: "#E67E22",
  h3FontSize: "24px",
  h3LineHeight: "1.4",
  h3Bold: true,
  paragraphFontSize: "18px",
  paragraphColor: "#454f5e",
  paragraphLineHeight: "1.8",
  linkColor: "#0066cc",
  linkTextDecoration: "none",
  linkFontWeight: "400",
  stripLinkBold: true,
  buttonBgColor: "#333333",
  buttonTextColor: "#ffffff",
  buttonBorderRadius: "4px",
  buttonPadding: "12px 30px",
  stripButtonStyle: false,
  listItemColor: "#454f5e",
  listItemFontSize: "18px",
  deduplicateLi: true,
  imageMaxWidth: "100%",
  imageBorderRadius: "0px",
  faqEnabled: false,
  faqH3Color: "",
  faqH3FontSize: "",
  faqH3Bold: true,
  faqLabelEnabled: false,
  faqLabelColor: "",
  faqLabelFontSize: "",
  emColor: "#ff0000",
  emBold: false,
  generateToc: true,
  tocTitle: "目錄❯",
  tocBgColor: "#f9f9f9",
  tocBgOpacity: 100,
  blogBaseUrl: "",
  specialNotes: "",
};

export const VJEWELRY_PRESET: Omit<ClientProfile, "id" | "name" | "createdAt" | "updatedAt"> = {
  h2Color: "#000000",
  h2FontSize: "24px",
  h2LineHeight: "1.4",
  h2Bold: true,
  h3Color: "#800080",
  h3FontSize: "20px",
  h3LineHeight: "1.4",
  h3Bold: true,
  paragraphFontSize: "17px",
  paragraphColor: "#454f5e",
  paragraphLineHeight: "1.8",
  linkColor: "#800080",
  linkTextDecoration: "underline",
  linkFontWeight: "400",
  stripLinkBold: true,
  buttonBgColor: "#333333",
  buttonTextColor: "#ffffff",
  buttonBorderRadius: "4px",
  buttonPadding: "12px 30px",
  stripButtonStyle: false,
  listItemColor: "#7a7a7a",
  listItemFontSize: "17px",
  deduplicateLi: true,
  imageMaxWidth: "100%",
  imageBorderRadius: "0px",
  faqEnabled: false,
  faqH3Color: "",
  faqH3FontSize: "",
  faqH3Bold: true,
  faqLabelEnabled: false,
  faqLabelColor: "",
  faqLabelFontSize: "",
  emColor: "#ff0000",
  emBold: false,
  generateToc: true,
  tocTitle: "目錄❯",
  tocBgColor: "#f9f9f9",
  tocBgOpacity: 100,
  blogBaseUrl: "",
  specialNotes: "",
};

export function createDefaultClient(name: string): ClientProfile {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    name,
    createdAt: now,
    updatedAt: now,
    ...DEFAULT_CLIENT_PROFILE,
  };
}
